apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: ActiveDirectoryAdministrator
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/activedirectoryadministrator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    login: sqladmin
    objectId: ${data.azurerm_client_config.current.object_id}
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverName: ${azurerm_mysql_server.example.name}
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: dbformysql/v1alpha1/activedirectoryadministrator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mysqladminun
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: example-resources
    skuName: B_Gen5_2
    sslEnforcementEnabled: true
    storageMb: 5120
    version: "5.7"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/activedirectoryadministrator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
