apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backupRetentionDays: 7
    delegatedSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: West Europe
    privateDnsZoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Standard_D2ds_v4

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: PrivateDNSZone
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: PrivateDNSZoneVirtualNetworkLink
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    privateDnsZoneNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.2.0/24
    delegation:
    - name: fs
      serviceDelegation:
      - actions:
        - Microsoft.Network/virtualNetworks/subnets/join/action
        name: Microsoft.DBforMySQL/flexibleServers
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpoints:
    - Microsoft.Storage
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
