apiVersion: dbformysql.azure.kubeform.com/v1alpha1
kind: FlexibleDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibledatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    charset: utf8
    collation: utf8_unicode_ci
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dbformysql.azure.kubeform.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibledatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mysqladminun
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: example-resources
    skuName: B_Standard_B1s

---

