apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServerConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    value: "600"

---

apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: adminTerraform
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: example-resources
    skuName: GP_Standard_D2ds_v4

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
