apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibledatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    charset: utf8
    collation: utf8_unicode_ci
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibledatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mysqladminun
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: B_Standard_B1s

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibledatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
