apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServerFirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    endIpAddress: 40.112.8.12
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    startIpAddress: 40.112.8.12

---

apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/flexibleserverfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
