apiVersion: dbformysql.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: dbformysql/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mysqladminun
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    autoGrowEnabled: true
    backupRetentionDays: 7
    geoRedundantBackupEnabled: false
    infrastructureEncryptionEnabled: false
    location: West Europe
    publicNetworkAccessEnabled: true
    resourceGroupName: ${azurerm_resource_group.example.name}
    skuName: B_Gen5_2
    sslEnforcementEnabled: true
    sslMinimalTlsVersionEnforced: TLS1_2
    storageMb: 5120
    version: "5.7"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformysql/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
