apiVersion: network.azure.kubedb.com/v1alpha1
kind: PrivateDNSZone
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/privatednszone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupName: ${azurerm_resource_group.example.name}

---

