apiVersion: network.azure.kubedb.com/v1alpha1
kind: PrivateDNSZoneVirtualNetworkLink
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/privatednszonevirtualnetworklink
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    privateDnsZoneNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: PrivateDNSZone
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/privatednszonevirtualnetworklink
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/privatednszonevirtualnetworklink
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/privatednszonevirtualnetworklink
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
