apiVersion: network.azure.kubedb.com/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/routetable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    disableBgpRoutePropagation: false
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    route:
    - addressPrefix: 10.1.0.0/16
      name: route1
      nextHopType: VnetLocal
    tags:
      environment: Production

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/routetable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
