apiVersion: network.azure.kubedb.com/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/securitygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    securityRule:
    - access: Allow
      destinationAddressPrefix: '*'
      destinationPortRange: '*'
      direction: Inbound
      name: test123
      priority: 100
      protocol: Tcp
      sourceAddressPrefix: '*'
      sourcePortRange: '*'
    tags:
      environment: Production

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/securitygroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
