apiVersion: network.azure.kubedb.com/v1alpha1
kind: SubnetRouteTableAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    route:
    - addressPrefix: 10.100.0.0/14
      name: example
      nextHopInIpAddress: 10.10.1.1
      nextHopType: VirtualAppliance

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.2.0/24
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
