apiVersion: network.azure.kubedb.com/v1alpha1
kind: SubnetNetworkSecurityGroupAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetnetworksecuritygroupassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    networkSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetnetworksecuritygroupassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    securityRule:
    - access: Allow
      destinationAddressPrefix: '*'
      destinationPortRange: '*'
      direction: Inbound
      name: test123
      priority: 100
      protocol: Tcp
      sourceAddressPrefix: '*'
      sourcePortRange: '*'

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetnetworksecuritygroupassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetnetworksecuritygroupassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.2.0/24
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnetnetworksecuritygroupassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
