apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetworkPeering
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/virtualnetworkpeering
  labels:
    testing.upbound.io/example-name: example-1
  name: example-1
spec:
  forProvider:
    remoteVirtualNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-2
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-1

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/virtualnetworkpeering
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/virtualnetworkpeering
  labels:
    testing.upbound.io/example-name: example-1
  name: example-1
spec:
  forProvider:
    addressSpace:
    - 10.0.1.0/24
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/virtualnetworkpeering
  labels:
    testing.upbound.io/example-name: example-2
  name: example-2
spec:
  forProvider:
    addressSpace:
    - 10.0.2.0/24
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
