apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: SQLFunction
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/sqlfunction
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    body: function trigger(){}
    containerIdRef:
      name: example-container

---