apiVersion: azure.kubedb.com/v1beta1
metadata:
  name: default
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      name: azure-secret
      key: creds
      namespace: crossplane-system
#az ad sp create-for-rbac --sdk-auth --role Owner --scopes <your-subscription-id>
#kubectl create secret generic azure-secret -n crossplane-system --from-file=creds=./azure-credentials.json