apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraKeySpace
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandrakeyspace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    throughput: 400

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandrakeyspace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    capabilities:
    - name: EnableCassandra
    consistencyPolicy:
    - consistencyLevel: Strong
    geoLocation:
    - failoverPriority: 0
      location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandrakeyspace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
