apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: CassandraTable
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cassandraKeyspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    schema:
    - column:
      - name: test1
        type: ascii
      - name: test2
        type: int
      partitionKey:
      - name: test1

---

apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    capabilities:
    - name: EnableCassandra
    consistencyPolicy:
    - consistencyLevel: Strong
    geoLocation:
    - failoverPriority: 0
      location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupName: tflex-cosmosdb-account-rg

---

apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: CassandraKeySpace
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: tfex-cosmosdb-account
    resourceGroupName: tflex-cosmosdb-account-rg
    throughput: 400

---

