apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraCluster
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandracluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    defaultAdminPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    delegatedManagementSubnetId: ${azurerm_subnet.example.id}
    location: West Europe
    resourceGroupName: ${azurerm_resource_group.example.name}

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandracluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandracluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupName: accexample-rg
