apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraDatacenter
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZonesEnabled: false
    cassandraClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    delegatedManagementSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    diskCount: 4
    location: West Europe
    nodeCount: 3
    skuName: Standard_DS14_v2

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraCluster
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    defaultAdminPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    delegatedManagementSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: authorization.azure.kubedb.com/v1alpha1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    principalId: ${data.azuread_service_principal.example.object_id}
    roleDefinitionName: Network Contributor
    scope: ${azurerm_virtual_network.example.id}

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.1.0/24
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/cassandradatacenter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
