apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: GremlinGraph
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: ${data.azurerm_cosmosdb_account.example.name}
    conflictResolutionPolicy:
    - conflictResolutionPath: /_ts
      mode: LastWriterWins
    databaseNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    indexPolicy:
    - automatic: true
      excludedPaths:
      - /"_etag"/?
      includedPaths:
      - /*
      indexingMode: consistent
    partitionKeyPath: /Example
    resourceGroupName: ${data.azurerm_cosmosdb_account.example.resource_group_name}
    throughput: 400
    uniqueKey:
    - paths:
      - /definition/id1
      - /definition/id2

---

apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: GremlinDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: ${data.azurerm_cosmosdb_account.example.name}
    resourceGroupName: ${data.azurerm_cosmosdb_account.example.resource_group_name}

---

