apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: GremlinGraph
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    conflictResolutionPolicy:
    - conflictResolutionPath: /_ts
      mode: LastWriterWins
    databaseNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    indexPolicy:
    - automatic: true
      excludedPaths:
      - /"_etag"/?
      includedPaths:
      - /*
      indexingMode: consistent
    partitionKeyPath: /Example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    throughput: 400
    uniqueKey:
    - paths:
      - /definition/id1
      - /definition/id2

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: GremlinDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
