apiVersion: cosmosdb.azure.kubeform.com/v1alpha1
kind: GremlinDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/gremlindatabase
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: ${data.azurerm_cosmosdb_account.example.name}
    resourceGroupName: ${data.azurerm_cosmosdb_account.example.resource_group_name}
    throughput: 400

---

