apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoCollection
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: ${data.azurerm_cosmosdb_account.example.name}
    databaseNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    defaultTtlSeconds: "777"
    index:
    - keys:
      - _id
      unique: true
    resourceGroupName: ${data.azurerm_cosmosdb_account.example.resource_group_name}
    shardKey: uniqueKey
    throughput: 400

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: ${data.azurerm_cosmosdb_account.example.name}
    resourceGroupName: ${data.azurerm_cosmosdb_account.example.resource_group_name}

---

