apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoCollection
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    databaseNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    defaultTtlSeconds: "777"
    index:
    - keys:
      - _id
      unique: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    shardKey: uniqueKey
    throughput: 400

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
