apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: SQLContainer
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/sqlcontainer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    databaseNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    indexingPolicy:
    - excludedPath:
      - path: /excluded/?
      includedPath:
      - path: /*
      - path: /included/?
      indexingMode: consistent
    partitionKeyPath: /definition/id
    partitionKeyVersion: 1
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    throughput: 400
    uniqueKey:
    - paths:
      - /definition/idlong
      - /definition/idshort

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: SQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/sqlcontainer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
