apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: cosmosdb/v1alpha1/table
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: azurerm_cosmosdb_account
    throughput: 400
