apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/account
  labels:
    testing.kubedb.com/example-name: db
  name: example-cosmosdb
spec:
  forProvider:
    capabilities:
      # - name: EnableGremlin
      # - name: EnableTable
      - name: EnableCassandra
    consistencyPolicy:
      - consistencyLevel: Strong
    enableAutomaticFailover: true
    geoLocation:
      - failoverPriority: 0
        location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupNameRef:
      name: db

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cosmosdb
  labels:
    testing.kubedb.com/example-name: db
  name: db
spec:
  forProvider:
    location: West Europe
---