apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraTable
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    cassandraKeyspaceIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    schema:
    - column:
      - name: test1
        type: ascii
      - name: test2
        type: int
      partitionKey:
      - name: test1

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.kubedb.com/example-name: cassandra
  name: example-cosmosdb-cassandra
spec:
  forProvider:
    capabilities:
    - name: EnableCassandra
    consistencyPolicy:
    - consistencyLevel: Strong
    geoLocation:
    - failoverPriority: 0
      location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: rg1

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: CassandraKeySpace
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: cassandra
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: rg1
    throughput: 400

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cassandratable
  labels:
    testing.kubedb.com/example-name: rg1
  name: example-cosmosdb
spec:
  forProvider:
    location: West Europe