apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: GremlinGraph
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: gremlin
    conflictResolutionPolicy:
    - conflictResolutionPath: /_ts
      mode: LastWriterWins
    databaseNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    indexPolicy:
    - automatic: true
      excludedPaths:
      - /"_etag"/?
      includedPaths:
      - /*
      indexingMode: consistent
    partitionKeyPath: /Example
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: rg1
    throughput: 400
    uniqueKey:
    - paths:
      - /definition/id1
      - /definition/id2

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.kubedb.com/example-name: gremlin
  name: example-cosmosdb-gremlin
spec:
  forProvider:
    capabilities:
      - name: EnableGremlin
    consistencyPolicy:
      - consistencyLevel: Strong
    geoLocation:
      - failoverPriority: 0
        location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: rg1

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: GremlinDatabase
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/gremlingraph
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: gremlin
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: rg1

---
apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/account
  labels:
    testing.kubedb.com/example-name: rg1
  name: rg1
spec:
  forProvider:
    location: West Europe