apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: SQLRoleDefinition
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/sqlroledefinition
    upjet.kubedb.com/manual-intervention: "This resource needs a valid assignableScopes id(s)."
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    assignableScopes:
    - "/subscriptions/1bfc9f66-316d-433e-b13d-c55589f642ca/resourceGroups/example/providers/Microsoft.DocumentDB/databaseAccounts/upbound-example"
    name: acctestsqlrole
    permissions:
    - dataActions:
      - Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/read
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example
    type: CustomRole
    # roleDefinitionId: 84cf3a8b-4122-4448-bce2-fa423cfe0a15

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/sqlroledefinition
    upjet.kubedb.com/manual-intervention: "This resource is dependency of SQLRoleDefinition. This resource is skipping because parent resource was skipped."
  labels:
    testing.kubedb.com/example-name: example
  name: upbound-example
spec:
  forProvider:
    consistencyPolicy:
    - consistencyLevel: Strong
    geoLocation:
    - failoverPriority: 0
      location: West Europe
    kind: GlobalDocumentDB
    location: West Europe
    offerType: Standard
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/sqlroledefinition
    upjet.kubedb.com/manual-intervention: "This resource is dependency of SQLRoleDefinition. This resource is skipping because parent resource was skipped."
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe