apiVersion: azure.kubedb.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    billingScopeId: ${data.azurerm_billing_enrollment_account_scope.example.id}
    subscriptionName: My Example EA Subscription
