apiVersion: authorization.azure.kubedb.com/v1alpha1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1alpha1/roleassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    principalId: ${data.azurerm_client_config.example.object_id}
    roleDefinitionName: Reader
    scope: ${data.azurerm_subscription.primary.id}
