apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    charset: UTF8
    collation: English_United States.1252
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    autoGrowEnabled: true
    backupRetentionDays: 7
    geoRedundantBackupEnabled: false
    location: West Europe
    resourceGroupName: api-rg-pro
    skuName: B_Gen5_2
    sslEnforcementEnabled: true
    storageMb: 5120
    version: "9.5"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

