apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: FirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/firewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    endIpAddress: 40.112.8.12
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    startIpAddress: 40.112.8.12

---

apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/firewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Gen5_2
    sslEnforcementEnabled: true
    version: "11"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/firewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
