apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: FlexibleServerConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: backslash_quote
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    value: "on"

---

apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: example-resources
    skuName: GP_Standard_D4s_v3
    storageMb: 32768
    version: "12"

---

