apiVersion: dbforpostgresql.azure.kubeform.com/v1alpha1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    delegatedSubnetId: ${azurerm_subnet.example.id}
    location: ${azurerm_resource_group.example.location}
    privateDnsZoneId: ${azurerm_private_dns_zone.example.id}
    resourceGroupName: ${azurerm_resource_group.example.name}
    skuName: GP_Standard_D4s_v3
    storageMb: 32768
    version: "12"
    zone: "1"

---

apiVersion: network.azure.kubeform.com/v1alpha1
kind: PrivateDNSZone
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupName: example-resources

---

apiVersion: network.azure.kubeform.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/flexibleserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupName: example-resources

---

