apiVersion: dbforpostgresql.azure.kubeform.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    autoGrowEnabled: true
    backupRetentionDays: 7
    geoRedundantBackupEnabled: true
    location: ${azurerm_resource_group.example.location}
    publicNetworkAccessEnabled: false
    resourceGroupName: ${azurerm_resource_group.example.name}
    skuName: GP_Gen5_4
    sslEnforcementEnabled: true
    sslMinimalTlsVersionEnforced: TLS1_2
    storageMb: 640000
    version: "11"

---

