apiVersion: dbforpostgresql.azure.kubeform.com/v1alpha1
kind: VirtualNetworkRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ignoreMissingVnetServiceEndpoint: true
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetId: ${azurerm_subnet.internal.id}

---

apiVersion: dbforpostgresql.azure.kubeform.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backupRetentionDays: 7
    location: West Europe
    resourceGroupName: example-resources
    skuName: GP_Gen5_2
    sslEnforcementEnabled: true
    storageMb: 5120
    version: "9.5"

---

apiVersion: network.azure.kubeform.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.7.29.0/29
    location: West Europe
    resourceGroupName: example-resources

---

