apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: VirtualNetworkRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ignoreMissingVnetServiceEndpoint: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: internal

---

apiVersion: dbforpostgresql.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backupRetentionDays: 7
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Gen5_2
    sslEnforcementEnabled: true
    storageMb: 5120
    version: "9.5"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: internal
  name: internal
spec:
  forProvider:
    addressPrefixes:
    - 10.7.29.0/29
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceEndpoints:
    - Microsoft.Sql
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.7.29.0/29
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
