apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstanceVulnerabilityAssessment
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation of MSSQLManagedInstance takes 4 hours"
  name: example
spec:
  forProvider:
    managedInstanceIdRef:
      name: examplesql
    recurringScans:
    - emailSubscriptionAdmins: true
      emails:
      - email@example1.com
      - email@example2.com
      enabled: true
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: crossplane-system
    storageContainerPath: https://crossplestoraccsql13722.blob.core.windows.net/example-storage-account
---
apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  name: example-storage-account
  annotations:
    crossplane.io/external-name: crossplestoraccsql13722
spec:
  forProvider:
    resourceGroupNameRef:
      name: db
    location: "West US"
    accountTier: "Standard"
    accountReplicationType: "LRS"
    tags:
      provisioner: crossplane
  writeConnectionSecretToRef:
    name: example-storage-account
    namespace: crossplane-system
---