apiVersion: keyvault.azure.kubedb.com/v1alpha1
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: keyvault/v1alpha1/vault
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    enabledForDiskEncryption: true
    location: ${azurerm_resource_group.example.location}
    purgeProtectionEnabled: false
    resourceGroupName: ${azurerm_resource_group.example.name}
    skuName: standard
    softDeleteRetentionDays: 7
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

