apiVersion: dbformariadb.azure.kubeform.com/v1alpha1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: interactive_timeout
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverName: ${azurerm_mariadb_server.example.name}
    value: "600"

---

apiVersion: dbformariadb.azure.kubeform.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mariadbadmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: api-rg-pro
    skuName: B_Gen5_2
    sslEnforcementEnabled: true
    version: "10.2"

---

