apiVersion: dbformariadb.azure.kubedb.com/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    charset: utf8mb4
    collation: utf8mb4_unicode_520_ci
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dbformariadb.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: acctestun
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backupRetentionDays: 7
    geoRedundantBackupEnabled: false
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: B_Gen5_2
    sslEnforcementEnabled: true
    storageMb: 51200
    version: "10.2"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/database
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
