apiVersion: dbformariadb.azure.kubedb.com/v1alpha1
kind: VirtualNetworkRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupName: ${azurerm_resource_group.example.name}
    serverName: ${azurerm_mariadb_server.example.name}
    subnetId: ${azurerm_subnet.internal.id}

---

apiVersion: dbformariadb.azure.kubedb.com/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mariadbadminun
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupName: example-resources
    skuName: GP_Gen5_2
    sslEnforcementEnabled: true
    version: "10.2"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1alpha1/virtualnetworkrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.7.29.0/29
    location: West Europe
    resourceGroupName: example-resources

---

