apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerVulnerabilityAssessment
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    recurringScans:
    - emailSubscriptionAdmins: true
      emails:
      - email@example1.com
      - email@example2.com
      enabled: true
    serverSecurityAlertPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: upbound-system
    storageContainerPath: ${azurerm_storage_account.example.primary_blob_endpoint}${azurerm_storage_container.example.name}/

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerSecurityAlertPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    state: Enabled

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservervulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    containerAccessType: private
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
