apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerMicrosoftSupportAuditingPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    retentionInDays: 6
    storageAccountAccessKeyIsSecondary: false
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: upbound-system
    storageEndpoint: ${azurerm_storage_account.example.primary_blob_endpoint}

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
