apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerTransparentDataEncryption
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservertransparentdataencryption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservertransparentdataencryption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    azureadAdministrator:
    - loginUsername: AzureAD Admin
      objectId: 00000000-0000-0000-0000-000000000000
    location: EastUs
    minimumTlsVersion: "1.2"
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      environment: production
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlservertransparentdataencryption
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: EastUs
