apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLElasticPool
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    licenseType: LicenseIncluded
    location: West Europe
    maxSizeGb: 756
    perDatabaseSettings:
    - maxCapacity: 4
      minCapacity: 0.25
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku:
    - capacity: 4
      family: Gen4
      name: BasicPool
      tier: Basic

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlelasticpool
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
