apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLFailoverGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlfailovergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    databasesRefs:
    - name: example
    partnerServer:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: secondary
    readWriteEndpointFailoverPolicy:
    - graceMinutes: 80
      mode: Automatic
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    tags:
      database: example
      environment: prod

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlfailovergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    maxSizeGb: "200"
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    skuName: S1

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlfailovergroup
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    version: "12.0"

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlfailovergroup
  labels:
    testing.upbound.io/example-name: secondary
  name: secondary
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlfailovergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
