apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstanceVulnerabilityAssessment
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstancevulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    managedInstanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    recurringScans:
    - emailSubscriptionAdmins: true
      emails:
      - email@example1.com
      - email@example2.com
      enabled: true
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: upbound-system
    storageContainerPath: ${azurerm_storage_account.example.primary_blob_endpoint}${azurerm_storage_container.example.name}/

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstancevulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: missadministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    licenseType: BasePrice
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Gen5
    storageSizeInGb: 32
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vcores: 4

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstancevulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstancevulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.2.0/24
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstancevulnerabilityassessment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
