apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobCredential
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    jobAgentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    username: my-username

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    collation: SQL_Latin1_General_CP1_CI_AS
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: S1

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobAgent
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: northeurope
    name: example-job-agent

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: northeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: northeurope
