apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mradministrator
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    licenseType: BasePrice
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Gen5
    storageSizeInGb: 32
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vcores: 4

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.0.0/24
    delegation:
    - name: managedinstancedelegation
      serviceDelegation:
      - actions:
        - Microsoft.Network/virtualNetworks/subnets/join/action
        - Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action
        - Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action
        name: Microsoft.Sql/managedInstances
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqlmanagedinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
