apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLOutboundFirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqloutboundfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServer
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqloutboundfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: 4dm1n157r470r
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    outboundNetworkRestrictionEnabled: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    version: "12.0"

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/mssqloutboundfirewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
