apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstanceVulnerabilityAssessment
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation of MSSQLManagedInstance takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example
spec:
  forProvider:
    managedInstanceIdRef:
      name: example-sql
    recurringScans:
    - emailSubscriptionAdmins: true
      emails:
      - email@example1.com
      - email@example2.com
      enabled: true
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: upbound-system
    storageContainerPath: https://crossplestoraccsql13722.blob.core.windows.net/example-storage-account
---
apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  name: example-storage-account
  annotations:
    crossplane.io/external-name: crossplestoraccsql13722
    upjet.kubedb.com/manual-intervention: "Creation of MSSQLManagedInstance takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
spec:
  forProvider:
    resourceGroupNameRef:
      name: example-sql-rg
    location: "West Europe"
    accountTier: "Standard"
    accountReplicationType: "LRS"
    tags:
      provisioner: crossplane
  writeConnectionSecretToRef:
    name: example-storage-account
    namespace: upbound-system