apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerTransparentDataEncryption
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservertransparentdataencryption
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    serverIdRef:
      name: mssqlservername

---
