apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerMicrosoftSupportAuditingPolicy
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    blobStorageEndpointSelector:
      matchLabels:
        testing.kubedb.com/example-name: staccexample0001
    serverIdSelector:
      matchLabels:
        testing.kubedb.com/example-name: example-srv
    storageAccountAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-storage-account
      namespace: crossplane-system
---
apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    uptest.kubedb.com/pre-delete-hook: testhooks/delete-supportauditingpolicy.sh
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlservermicrosoftsupportauditingpolicy
  labels:
    testing.kubedb.com/example-name: staccexample0001
  name: staccexample0001
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.kubedb.com/example-name: mssql-rg
  writeConnectionSecretToRef:
    name: example-storage-account
    namespace: crossplane-system
---