apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLServerSecurityAlertPolicy
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqlserversecurityalertpolicy
  labels:
    testing.kubedb.com/example-name: example
  name: alertpolicyname
spec:
  forProvider:
    disabledAlerts:
    - Sql_Injection
    - Data_Exfiltration
    resourceGroupNameRef:
      name: db
    retentionDays: 0
    serverNameRef:
      name: mssqlservername
    state: Enabled

---
