apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstanceFailoverGroup
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation takes 4 hours"
  name: example-sql-managed-failover
spec:
  forProvider:
    location: West US
    managedInstanceIdRef:
      name: examplesql
    partnerManagedInstanceIdRef:
      name: example-sql-failover-instance
    readWriteEndpointFailoverPolicy:
    - graceMinutes: 60
      mode: Automatic
---
#Error
#observe failed: cannot run plan: plan failed: Instance cannot be destroyed: Resource azurerm_mssql_managed_instance.example-sql-failover-instance has lifecycle.prevent_destroy set,
# but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or 
#reduce the scope of the plan using the -target flag.
apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLManagedInstance
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation takes 4 hours"
  name: example-sql-failover-instance
spec:
  forProvider:
    dnsZonePartnerIdRef:
      name: examplesql
    administratorLogin: mradministrator
    administratorLoginPasswordSecretRef:
      key: password
      name: example-secret
      namespace: crossplane-system
    licenseType: BasePrice
    location: North Europe
    resourceGroupNameRef:
      name: example-sql-rg-failover
    skuName: GP_Gen5
    storageSizeInGb: 32
    subnetIdRef:
      name: example-subnet-failover
    vcores: 4
    identity:
      - type: SystemAssigned
---
#Error
# apply failed: creating Instance Failover Group: (Name "example-sql-managed-failover" / Location Name "West Europe" / Resource Group "example-sql-rg"): 
# sql.InstanceFailoverGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: Code="ConflictingServerOperation"
#  Message="Server 'example-sql-failover-instance' is busy with another operation. Please try your operation later.": creating Instance Failover Group: 
#  (Name "example-sql-managed-failover" / Location Name "West Europe" / Resource Group "example-sql-rg"): sql.InstanceFailoverGroupsClient#CreateOrUpdate: 
#  Failure sending request: StatusCode=409 -- Original Error: Code="ConflictingServerOperation" Message="Server 'example-sql-failover-instance' is busy with another operation.
#   Please try your operation later."
apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  name: example-sql-rg-failover
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
spec:
  forProvider:
    location: North Europe
    tags:
      provisioner: crossplane
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetwork
metadata:
  name: example-vn-failover
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
spec:
  forProvider:
    location: North Europe
    resourceGroupNameRef:
      name: example-sql-rg-failover
    addressSpace:
      - "10.1.0.0/16"
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: Subnet
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-subnet-failover
spec:
  forProvider:
    resourceGroupNameRef:
      name: example-sql-rg-failover
    virtualNetworkNameRef:
      name: example-vn-failover
    addressPrefixes:
      - "10.1.0.0/24"
    delegation:
      - name: managedinstancedelegation
        serviceDelegation:
          - name: "Microsoft.Sql/managedInstances"
            actions:
              - "Microsoft.Network/virtualNetworks/subnets/join/action"
              - "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"
              - "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-failover
spec:
  forProvider:
    location: North Europe
    resourceGroupNameRef:
      name: example-sql-rg-failover
    tags:
      environment: Production
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: SubnetNetworkSecurityGroupAssociation
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-failover
spec:
  forProvider:
    networkSecurityGroupIdRef:
      name: example-failover
    subnetIdRef:
      name: example-subnet-failover
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: RouteTable
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-failover
spec:
  forProvider:
    disableBgpRoutePropagation: false
    location: North Europe
    resourceGroupNameRef:
      name: example-sql-rg-failover
    tags:
      environment: Production
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: SubnetRouteTableAssociation
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-failover
spec:
  forProvider:
    routeTableIdRef:
      name: example-failover
    subnetIdRef:
      name: example-subnet-failover
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetworkPeering
metadata:
  name: example
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
spec:
  forProvider:
    remoteVirtualNetworkIdRef:
      name: example-vn-failover
    resourceGroupNameRef:
      name: db
    virtualNetworkNameRef:
      name: example-vn
---
apiVersion: network.azure.kubedb.com/v1alpha1
kind: VirtualNetworkPeering
metadata:
  annotations:
    upjet.kubedb.com/manual-intervention: "Creation MSSQLManagedInstanceFailoverGroup takes 4 hours, see https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration"
  name: example-failover
spec:
  forProvider:
    remoteVirtualNetworkIdRef:
      name: example-vn
    resourceGroupNameRef:
      name: example-sql-rg-failover
    virtualNetworkNameRef:
      name: example-vn-failover

---