
apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobAgent
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqljobagent
  labels:
    testing.kubedb.com/example-name: examplemssqljobagent
  name: examplemssqljobagent
spec:
  forProvider:
    databaseIdRef:
      name: database
    location: West Europe
    name: example-job-agent

---
