apiVersion: sql.azure.kubedb.com/v1alpha1
kind: MSSQLJobCredential
metadata:
  annotations:
    meta.kubedb.com/example-id: sql/v1alpha1/mssqljobcredential
  labels:
    testing.kubedb.com/example-name: examplemssqljobcred
  name: examplemssqljobcred
spec:
  forProvider:
    jobAgentIdRef:
      name: examplemssqljobagent
    passwordSecretRef:
      key: example-key
      name: example-secret-job
      namespace: crossplane-system
    username: my-username

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret-job
  namespace: crossplane-system
type: Opaque
data:
  example-key: dGVzdFBhc3N3b3JkITEyMw==