apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoCollection
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.kubedb.com/example-name: example
  name: example-mongo-collection
spec:
  forProvider:
    accountNameRef:
      name: example-cosmosdb-mongo
    databaseNameRef:
      name: example
    resourceGroupNameRef:
      name: db
    defaultTtlSeconds: 777
    index:
    - keys:
      - _id
      unique: true
    shardKey: uniqueKey
    throughput: 400

---