

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: MongoDatabase
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameRef:
      name: example-cosmosdb-mongo
    resourceGroupNameRef:
      name: db

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/mongocollection
  labels:
    testing.kubedb.com/example-name: mongo
  name: example-cosmosdb-mongo
spec:
  forProvider:
    capabilities:
      - name: EnableMongo
      - name: MongoDBv3.4
      - name: mongoEnableDocLevelTTL
    consistencyPolicy:
      - consistencyLevel: Strong
    geoLocation:
      - failoverPriority: 0
        location: West Europe
    kind: MongoDB
    location: West Europe
    offerType: Standard
    resourceGroupNameRef:
      name: db

---
apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cosmosdb
  labels:
    testing.kubedb.com/example-name: db
  name: db
spec:
  forProvider:
    location: West Europe
---