apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/account
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      environment: staging

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/account
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
