apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/container
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    containerAccessType: private
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/container
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/container
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      environment: staging
