apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Table
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/table
  labels:
    testing.kubedb.com/example-name: example
  name: example
spec:
  forProvider:
    accountNameRef:
      name: example-cosmosdb-table
    resourceGroupNameRef:
      name: db
    throughput: 400

---

apiVersion: cosmosdb.azure.kubedb.com/v1alpha1
kind: Account
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/table
  labels:
    testing.kubedb.com/example-name: table
  name: example-cosmosdb-table
spec:
  forProvider:
    capabilities:
      - name: EnableTable
    consistencyPolicy:
      - consistencyLevel: Strong
    geoLocation:
      - failoverPriority: 0
        location: West Europe
    location: West Europe
    offerType: Standard
    resourceGroupNameRef:
      name: db
---

apiVersion: azure.kubedb.com/v1alpha1
kind: ResourceGroup
metadata:
  annotations:
    meta.kubedb.com/example-id: cosmosdb/v1alpha1/cosmosdb
  labels:
    testing.kubedb.com/example-name: db
  name: db
spec:
  forProvider:
    location: West Europe
---